export const defaultValues = {
  phone: "",
  birthday: "",
  occupation: "",
  emergencyContact: "",
  address: "",
  medication: "",
  otherPhysicalActivity: "",
  head: false,
  neck: false,
  leftShoulder: false,
  RightShoulder: false,
  leftArm: false,
  rightArm: false,
  upperback: false,
  loweback: false,
  leftLeg: false,
  rightLeg: false,
  circulatory: false,
  digestive: false,
  skin: false,
  urinary: false,
  lymphatic: false,
  nervouse: false,
  muscular: false,
  skeletal: false,
  ebdocrine: false,
  respiratory: false,
  avoidAreas: "",
  goals: "",

  appointment: "none yet",
};
